version: '3'

services:
  mysql:
    container_name: 'mysql_local'
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=image-database
      - TZ=America/Sao_Paulo
      - LANG=C.UTF_8
    volumes:
      - /home/random-image-api/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
